### PR TITLE
start updates for  Y2 SONATA

### PR DESCRIPTION
**Pull request by stevenvanrossem**
- fix E-LAN deployment via dummy gatekeeper
- expose resource control via rest api
- expose connected datacenter interface name for a vnf when querying the status

### CODE REVIEW

**Comment by mpeuster** [comment]
We will delay the merge until Jenkins is back.

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
this error does not happen locally ... I'll check the details

**Comment by mpeuster** [comment]
checked it, error really seems to be related to this PR. something in the GK service start test was changed.
@stevenvanrossem do the test work on your dev machine?

**Comment by stevenvanrossem** [comment]
this will also require the containernet version with the latest pull request (using latest docker python API)

**Comment by stevenvanrossem** [comment]
test this please

**Comment by mpeuster** [comment]
@stevenvanrossem The changed docker version of this PR seems to make some trouble in our Jenkins: https://jenkins.sonata-nfv.eu/job/son-emu/184/console

Any suggestions?

**Comment by stevenvanrossem** [comment]
it seems jenkins is getting containernet from older location: mpeuster/containernet:latest
I think it is in misc/utils/Dockerfile   I'll adapt it...

**Comment by stevenvanrossem** [comment]
wait, @mpeuster is there an automated docker build of the new containernet/containernet repo?

**Comment by mpeuster** [comment]
Closing this PR.

All its changes are moved to https://github.com/sonata-nfv/son-emu/pull/194 to work with the new Jenkins test integration.

**Pull request closed without merging**
