### PR TITLE
Removing subshell for compatibility with Jenkins

### PR DESCRIPTION
**Pull request by cgeoffroy**
Modifying a test script to make it more compatible with Jenkins

### CODE REVIEW

**Comment by mpeuster** [comment]
@cgeoffroy I had disabled you script in Jenkins yesterday. Its now enabled again. So the test should run again.

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
comment trigger does not seem to work. maybe you can create a small commit?

**Comment by cgeoffroy** [comment]
The test is stable on Jenkins now

**Pull request merged**
