### PR TITLE
Added a simple dashboard for demos

### PR DESCRIPTION
**Pull request by mpeuster**
In order to prepare a demo is started a simple web-based dashboard which shows the same information like `son-emu-cli * list` but has an auto refresh and looks nicer than terminal windows.

We might extend this with functionality to start/stop/manage containers. But it has no high prio.

[Screenshot](https://github.com/mpeuster/son-emu/raw/master/dashboard/son-emu-dashboard-screenshot.png)

### CODE REVIEW

**Comment by mpeuster** [comment]
test this please

**Comment by felipevicens** [comment]
retest this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
retest this please

**Pull request merged**
